export const HighestDegree = [
    "Bachelor's",
    "Master's",
    "PhD",
    "High School (12th)",
    "School (10th)",
    "Diploma",
    "Postgraduate Diploma",
    "Diploma",
    "Other"
]

export const Subjects = [
    "Mathematics",
    "Science",
    "Geography",
    "History",
    "Music",
    "Sports",
    "Physics",
    "Chemistry",
    "Biology",
    "Economics",
    "Computer Science",
    "English",
    "Literature",
    "Political Science",
    "Psychology",
    "Sociology",
    "Philosophy",
    "Art",
    "Drama",
    "Environmental Studies",
    "Physical Education",
    "Business Studies",
    "Accounting",
    "Marketing",
    "Astronomy",
    "Ethics",
    "Civics",
    "Health Education",
    "Design and Technology",
    "Languages"
];